atlas_uri: mongodb+srv://Experimental:0ksnmQj15YqZD5DI@uwinuseast.86ldfsv.mongodb.net/?retryWrites=true&w=majority
db: Experimental
bucket: uwin-connect-media-storage
collections: { users: USERS, sessions: USER_SESSIONS, posts: POSTS }
