atlas_uri: mongodb+srv://UWinConnect-Backend:pOhjth3elH06kG5O@uwinuseast.86ldfsv.mongodb.net/?retryWrites=true&w=majority
db: DEV
bucket: uwin-connect-media-storage
collections: { users: USERS, sessions: USER_SESSIONS, posts: POSTS }
